services:
  api:
    build: ./api
    ports:
      - 3000/3000
    volumes:
      - api_data:/api
  db:
    image: postgres:15.2-alpine
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - intodo_db:/var/lib/postgres/data
      - /app/node_modules

volumes:
  intodo_db:
  api_data: