services:
  # api:
  #   build: ./api
  #   ports:
  #     - 3005:3000
  #   volumes:
  #     - ./api:/app
  #     - /app/node_modules
  db:
    image: postgres:15.2-alpine
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - intodo_db:/var/lib/postgres/data

volumes:
  intodo_db: